name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test:
    name: Test matrix (lint + pytest)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip and install base deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Install dev dependencies (if present)
        run: |
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install pytest black flake8 isort; fi

      - name: Lint (black / isort / flake8)  # optional but recommended
        run: |
          set -e
          black --version || pip install black
          isort --version || pip install isort
          flake8 --version || pip install flake8
          black --check .
          isort --check-only .
          flake8 .

      - name: Run tests (pytest)
        run: |
          pytest -q

      - name: Post-run summary
        if: success()
        run: echo "CI successful on Python ${{ matrix.python-version }}"
